"""remember teams picked but not yet played

Revision ID: 5f4ac6aefe4a
Revises: e961ce24cb75
Create Date: 2026-09-04 07:27:40.541979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f4ac6aefe4a'
down_revision: Union[str, None] = 'e961ce24cb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_teams', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('pending_teams')

    # ### end Alembic commands ###
