"""optional WMP and MMP designations

Both columns are nullable and nothing is backfilled: a league that never plays
coed carries two empty columns and behaves exactly as it did. Ratings are
untouched, so no replay is needed after this runs.

Revision ID: 6fd943c7d91e
Revises: 5f4ac6aefe4a
Create Date: 2026-09-04 10:29:50.116971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6fd943c7d91e'
down_revision: Union[str, None] = '5f4ac6aefe4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(), nullable=True))

    with op.batch_alter_table('session_players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation_override', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_players', schema=None) as batch_op:
        batch_op.drop_column('designation_override')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('designation')

    # ### end Alembic commands ###
