"""initial schema

Revision ID: e961ce24cb75
Revises: 
Create Date: 2026-09-03 21:28:40.504778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e961ce24cb75'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('merged_into', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['merged_into'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index('ux_players_active_name', ['name'], unique=True, sqlite_where=sa.text('active = 1'))

    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('player_season_ratings',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('mu', sa.Float(), nullable=False),
    sa.Column('sigma', sa.Float(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'season_id')
    )
    with op.batch_alter_table('player_season_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_season_ratings_season_id'), ['season_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_season_id'), ['season_id'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('players_on_field', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_session_id'), ['session_id'], unique=False)

    op.create_table('session_players',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('session_id', 'player_id')
    )
    op.create_table('game_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_index', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_index', name='ux_game_teams_game_index')
    )
    with op.batch_alter_table('game_teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_teams_game_id'), ['game_id'], unique=False)

    op.create_table('rating_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('mu_before', sa.Float(), nullable=False),
    sa.Column('sigma_before', sa.Float(), nullable=False),
    sa.Column('mu_after', sa.Float(), nullable=False),
    sa.Column('sigma_after', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='ux_rating_history_player_game')
    )
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_history_game_id'), ['game_id'], unique=False)
        batch_op.create_index('ix_rating_history_player_season', ['player_id', 'season_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_history_season_id'), ['season_id'], unique=False)

    op.create_table('game_team_players',
    sa.Column('game_team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_team_id'], ['game_teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('game_team_id', 'player_id')
    )
    with op.batch_alter_table('game_team_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_team_players_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_team_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_team_players_player_id'))

    op.drop_table('game_team_players')
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_history_season_id'))
        batch_op.drop_index('ix_rating_history_player_season')
        batch_op.drop_index(batch_op.f('ix_rating_history_game_id'))

    op.drop_table('rating_history')
    with op.batch_alter_table('game_teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_teams_game_id'))

    op.drop_table('game_teams')
    op.drop_table('session_players')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_session_id'))

    op.drop_table('games')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_season_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('player_season_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_season_ratings_season_id'))

    op.drop_table('player_season_ratings')
    op.drop_table('seasons')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index('ux_players_active_name', sqlite_where=sa.text('active = 1'))

    op.drop_table('players')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
